[project]
name = "wiki"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asgiref==3.8.1",
    "django==5.1.3",
    "markdown2==2.5.1",
    "sqlparse==0.5.1",
]
